---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
##permalink: / ## disables post output
timezone: null
lsi: false
markdown: kramdown
highlighter: rouge


### content configuration ###
title:       "Workhorse || Friends of AIGA"
keywords:    "SinglePaged, jekyll, template, github, blog, single page"
description: "Friends of AIGA End of Year Party"
url: "http://workhorse.github.io/"
favicon:     "img/favicon.ico"
google_analytics_key: UA-76137291-4  ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'

kramdown:
  auto_ids:  false
